debug: lab1.cpp
	g++ -Wpedantic -Wall -Wextra -Winit-self -Winline -Wconversion -Weffc++ -Wstrict-null-sentinel -Wnoexcept -Wctor-dtor-privacy -Woverloaded-virtual -Wconversion -Wsign-promo -Wzero-as-null-pointer-constant -g -o lab1-debug lab1.cpp
release: lab1.cpp
	g++ -o lab1-release lab1.cpp
